[package]
name = "aegeri-process"
version = { workspace = true }
edition = "2021"
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aegeri-message = { workspace = true }
parabyzantine = { workspace = true }
gossamer = { workspace = true }
gwrdfa-resample = { workspace = true }
thiserror = { workspace = true }
fuste-ecall-dispatcher = { workspace = true }
fuste-exit = { workspace = true }
fuste-exit-system = { workspace = true }
fuste-interrupt-handler = { workspace = true }
fuste-lilbug = { workspace = true }
fuste-riscv-core = { workspace = true }
fuste-riscv-elf = { workspace = true }
fuste-std-output-system = { workspace = true }

[lints]
workspace = true