[workspace]

resolver = "2"

members = [
  "gwrdfa/parabyzantine",
  "gwrdfa/container",
  "gwrdfa/resample/core",
  "gwrdfa/gossamer", 

  # aegeri
  "aegeri/message",
  "aegeri/process",
  "aegeri/full-client",
  "aegeri/cli"
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT"
authors = ["Ramate LLC"]
repository = "www.github.com/ramate/fuste"
homepage = "www.github.com/ramate/fuste"
publish = false
rust-version = "1.85.0"



[workspace.dependencies]
log = "0.4.29"
anyhow = "1.0"
futures = "0.3.17"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
thiserror = "1.0.50"
goblin = { version = "0.10.3" }
clap = { version = "4.4.10", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
syn = { version = "2.0", features = ["full"] }
quote = "1.0.23"
proc-macro2 = "1.0.32"
paste = { version = "1.0", default-features = false }
libp2p = { version = "0.53.2" }
ml-dsa = { version = "0.1.0-rc.7" }
sha3 = { version = "0.10.8" }
hex = "0.4.3"
env_logger = "0.11.9"
dotenv = "0.15.0"


orfile = { git = "https://github.com/movementlabsxyz/orfile.git", rev = "d02299214e5aa202130cd1eb9593ce8064d1ec69" }
orfile-util = { git = "https://github.com/movementlabsxyz/orfile.git", rev = "d02299214e5aa202130cd1eb9593ce8064d1ec69" }
orfile-macro = { git = "https://github.com/movementlabsxyz/orfile.git", rev = "d02299214e5aa202130cd1eb9593ce8064d1ec69" }
clap-markdown-ext = { git = "https://github.com/movementlabsxyz/clap-markdown-ext.git", rev = "8f54fe424504bf37fb01dc69aaed8166e429fe6a"}

parabyzantine = { path = "gwrdfa/parabyzantine" }
gwrdfa-container = { path = "gwrdfa/container" }
gossamer = { path = "gwrdfa/gossamer" }
gwrdfa-resample = { path = "gwrdfa/resample/core" }

aegeri-message = { path = "aegeri/message" }
aegeri-process = { path = "aegeri/process" }
aegeri-full-client = { path = "aegeri/full-client" }

fuste-ecall-dispatcher = { git = "https://github.com/ramate-io/fuste.git", rev = "e6fba8cc663ffbc42ebc6c7a00f179578b45145b" }
fuste-exit = { git = "https://github.com/ramate-io/fuste.git", rev = "e6fba8cc663ffbc42ebc6c7a00f179578b45145b" }
fuste-exit-system = { git = "https://github.com/ramate-io/fuste.git", rev = "e6fba8cc663ffbc42ebc6c7a00f179578b45145b" }
fuste-interrupt-handler = { git = "https://github.com/ramate-io/fuste.git", rev = "e6fba8cc663ffbc42ebc6c7a00f179578b45145b" }
fuste-lilbug = { git = "https://github.com/ramate-io/fuste.git", rev = "e6fba8cc663ffbc42ebc6c7a00f179578b45145b" }
fuste-riscv-core = { git = "https://github.com/ramate-io/fuste.git", rev = "e6fba8cc663ffbc42ebc6c7a00f179578b45145b" }
fuste-riscv-elf = { git = "https://github.com/ramate-io/fuste.git", rev = "e6fba8cc663ffbc42ebc6c7a00f179578b45145b" }
fuste-std-output-system = { git = "https://github.com/ramate-io/fuste.git", rev = "e6fba8cc663ffbc42ebc6c7a00f179578b45145b" }



[workspace.lints.clippy]
debug_assert_with_mut_call = "deny"
inefficient_to_string = "deny"
map_flatten = "deny"
manual_ok_or = "deny"
doc_link_with_quotes = "deny"
match_same_arms = "deny"
semicolon_if_nothing_returned = "deny"
unwrap_used = "warn"
expect_used = "warn"

[profile.dev]
panic = "unwind"

[profile.release.build-override]
opt-level = 3

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
