[package]
name = "gossamer"
version = { workspace = true }
edition = "2021"
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[features]
default = ["gossamer-logging"]
gossamer-logging = []

[dependencies]
parabyzantine = { workspace = true }
libp2p = { workspace = true, features = [
    "tcp",
    "dns",
    "noise",
    "yamux",
    "kad",
    "gossipsub",
    "macros",
    "async-std",
    "ping"
] }
tokio = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
gwrdfa-container = { workspace = true }
log = { workspace = true }

[lints]
workspace = true