[package]
name = "gwrdfa-resample"
version = { workspace = true }
edition = "2021"
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[features]
default = ["std"]
std = ["dep:gwrdfa-container"]

[dependencies]
parabyzantine = { workspace = true }
gwrdfa-container = { workspace = true, optional = true }

[dev-dependencies]
anyhow = { workspace = true }

[lints]
workspace = true