[package]
name = "gwrdfa-resample"
version = { workspace = true }
edition = "2021"
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
parabyzantine = { workspace = true }

[lints]
workspace = true