# This workflow runs cargo test on every pushed commit.

name: Cargo Test Ignored (Resource Acquiring)

on:
  push:
    branches:

jobs:
  cargo-test:
    uses: ./.github/workflows/nix-command.yml
    with:
      command: RUST_BACKTRACE=full cargo test --release -- --ignored
      nix_flake_path: '.'
      runner: 'ubuntu-latest'